### ISSUE TITLE
Support --version flag for iambic CLI.

### ISSUE THREAD

**Issue by rjulian** [noqdev/iambic#378]
**Is your feature request related to a problem? Please describe.**
If I'm working with the CLI locally, I should know which version of the tool I'm using.

**Describe the solution you'd like**
`iambic --version`
> iambic version 0.5.2

**Describe alternatives you've considered**
`pip list | grep iambic`

**Comment by datfinesoul** [comment]
Thank you for adding this to iambic.  This seems to have been added already at least in version 0.7.5.

**Comment by smoy** [comment]
This is released in pypi now.

```
(env) stevenmoy@steven-noqdev-mbp iambic_0_8_1 % iambic --version
iambic, version 0.8.1
```
