### ISSUE TITLE
Add help text to all commands

### ISSUE THREAD

**Issue by Will-NOQ** [noqdev/iambic#389]
Add help text to all commands to make the purpose of the command clearer. 

Additional improvements to be made as part of this issue:
- In the wizard, remove the "Ensure you're using AWS Org..." prompt because it's redundant
- Make it clearer that the template must be provided on plan and apply

**Comment by Wilhite-r** [comment]
Hello, can I be assigned to this ticket? This is referring to the CLI commands in `iambic/main.py`, correct?

**Comment by smoy** [comment]
@Wilhite-r wow, sure. Appreciate your contribution.

**Comment by castrapel** [comment]
Completed by #510
