### ISSUE TITLE
Add optional tag support to the CloudFormation templates

### ISSUE THREAD

**Issue by Will-NOQ** [noqdev/iambic#390]
Many orgs have tagging requirements for their IAM roles. In the wizard, before actually creating the roles using CloudFormation, add an option to allow tags to be assigned to the resource. This will require changes to the HubRole and SpokeRole templates as well as the prompt(s) in the wizard.

**Comment by smoy** [comment]
The ability to add tags during wizard AWS setup has been introduced in version 0.7.1
