### ISSUE TITLE
Provide a seamless Github App installation experience

### ISSUE THREAD

**Issue by smoy** [noqdev/iambic#402]
**Is your feature request related to a problem? Please describe.**
IAMbic Github installation is pretty manual according to docs. [GitHub App Manifest](https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/creating-a-github-app-from-a-manifest) maybe able to make the process much more seamless.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.](https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/creating-a-github-app-from-a-manifest)

**Describe alternatives you've considered**

**Additional context**

**Comment by mxw-sec** [comment]
Could this potentially be an included command??  Such as plan..  maybe iambic integration

Then a it asks a series of questions, and provides an output file for Terraform and github, and if you expand you could just add other walk through options like using Azure automation for Azure users instead of Lambda..

Then it gives you the steps to apply the customized files to your github application??

**Comment by smoy** [comment]
Not exactly seamless, but could be an improvement. 

I capture most of the required setting into the query params for new app creation

https://github.com/organizations/noqdev/settings/apps/new?name=iambic-integration-for-orgname&description=iambic-github-integration&url=https%3A%2F%2Fnoq.dev%2F&webhook_active=false&events[]=meta&events[]=issue_comment&&events[]=pull_request&contents=write&pull_requests=write&issues=write

**Comment by smoy** [comment]
The [docs](https://docs.iambic.org/getting_started/github#create-a-github-app-in-your-organization) now reference a link that includes most of the query params to create the App. Hopefully this makes installation simpler. It is not exactly seamless  because we still need the user to update the org name.

Some future improvement can be incorporate the flow to the wizard, so we can dynamically generate the URI with the org name input by the user.
