### ISSUE TITLE
Automatically Detect Management Account for AWS Organizations to confirm an existing prompt.

### ISSUE THREAD

**Issue by datfinesoul** [noqdev/iambic#405]
**Is your feature request related to a problem? Please describe.**
During the `iambic setup` process for AWS Organizations, the following prompt appears:
```text
If you would like to use AWS Organizations, the IAMbic hub account you configured must be the same AWS account as your AWS Organization.
? Is this the case? (Y/n)
```
This happens after the current **Account ID** has already been entered, and **AWS Organizations** has been selected.

**Describe the solution you'd like**
This prompt could be skipped since this information should be available at this step of the wizard already, and instead the SDK could be used to detect it, and issue a warning, that if the current account is not the same as the management account, the user needs to switch or provide alternate credentials.

`aws organizations describe-organization` returns the following kind of info that helps with this.

```json
{
    "Organization": {
        "Id": "o-nnnnnnnnnn",
        "Arn": "arn:aws:organizations::000000000000:organization/o-nnnnnnnnnn",
        "FeatureSet": "ALL",
        "MasterAccountArn": "arn:aws:organizations::000000000000:account/o-nnnnnnnnnn/000000000000",
        "MasterAccountId": "000000000000",
        "MasterAccountEmail": "admin@mydomainforaws.com",
        "AvailablePolicyTypes": [
            {
                "Type": "SERVICE_CONTROL_POLICY",
                "Status": "ENABLED"
            }
        ]
    }
}
```

**Describe alternatives you've considered**
- One alternative would be to just answer the question again
- Another alternative would be to make the message a bit more clear.  Something like
  ```
  You have previously selected AWS Organizations.  Please make sure that selected IAMbic hub account ID 000000000000 is also the AWS Organization's management account
  ```

**Additional context**

**Comment by datfinesoul** [comment]
Not sure if I should create another ticket, but the same thing applies to this prompt as well:
```text
This requires that you have the ability to create CloudFormation stacks, stack sets, and stack set instances.
If you are using an AWS Organization, be sure that trusted access is enabled.
You can check this using the AWS Console:
  https://ap-northeast-1.console.aws.amazon.com/organizations/v2/home/services/CloudFormation%20StackSets
? Proceed? (Y/n)
```

Using `aws organizations list-aws-service-access-for-organization` this information could be obtained as well by checking for:

```json
{
    "EnabledServicePrincipals": [
        {
            "ServicePrincipal": "member.org.stacksets.cloudformation.amazonaws.com",
            "DateEnabled": "2023-05-02T13:17:25.526000+09:00"
        }
    ]
}

```

**Comment by Will-NOQ** [comment]
Thanks for bringing up this suggestion as well as 406 and 407 up! We have someone taking a look at them now 😄

**Comment by smoy** [comment]
Thank you @datfinesoul for the report. We've included the fix in main branch. We will cut the pypi release in the regular scheduled schedule (once every 2 weeks)
