### ISSUE TITLE
AWS IAM Delete File issue Github APP

### ISSUE THREAD

**Issue by mxw-sec** [noqdev/iambic#419]
**Describe the bug**
Deleted an AWS IAM role 

**To Reproduce**

1. import AWS IAM roles using iambic import
2. Create some new files, but also delete a file
3. create a Pull request in Github, then run iambic apply
4. then FAIL

**Expected behavior**
create other accounts, "un-manage" the old account.

```
 File "/app/iambic/core/models.py", line 553, in delete
   repo = Repo(self.file_path, search_parent_directories=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/git/repo/base.py", line 213, in __init__
   raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /tmp/lambdaws6b38a5/.iambic/repos/resources/aws/iam/role/xxx-xxxx/assume-ecs-roles2.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/iambic/plugins/v0_1_0/github/github.py", line 370, in handle_iambic_git_apply
   template_changes = run_git_apply(
                      ^^^^^^^^^^^^^^
 File "/app/iambic/main.py", line 283, in run_git_apply
   template_changes = asyncio.run(
                      ^^^^^^^^^^^^
 File "/Python-3.11.1/Lib/asyncio/runners.py", line 190, in run
   return runner.run(main)
          ^^^^^^^^^^^^^^^^
 File "/Python-3.11.1/Lib/asyncio/runners.py", line 118, in run
   return self._loop.run_until_complete(task)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Python-3.11.1/Lib/asyncio/base_events.py", line 653, in run_until_complete
   return future.result()
          ^^^^^^^^^^^^^^^
 File "/app/iambic/request_handler/git_apply.py", line 82, in apply_git_changes
   template_changes = await config.run_apply(
                      ^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/iambic/config/dynamic_config.py", line 277, in run_apply
   template_changes = await asyncio.gather(*tasks)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/iambic/plugins/v0_1_0/aws/handlers.py", line 256, in apply
   template_changes = list(chain.from_iterable(await asyncio.gather(*tasks)))
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/iambic/plugins/v0_1_0/aws/handlers.py", line 205, in apply_iam_templates
   await async_batch_processor(
 File "/app/iambic/core/utils.py", line 229, in async_batch_processor
   return await asyncio.gather(*tasks, return_exceptions=return_exceptions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/iambic/plugins/v0_1_0/aws/models.py", line 809, in apply
   self.delete()
 File "/app/iambic/core/models.py", line 569, in delete
   os.remove(self.file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lambdaws6b38a5/.iambic/repos/resources/aws/iam/role/xxx-xxxx/assume-ecs-roles2.yaml'
```

- AWS Lambda function integrated with Github

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.

**Comment by castrapel** [comment]
By default, IAMbic will capture the state of all IAM, but doesn't need to manage all of it. Based on our conversation, I think you'd like to instruct IAMbic to ignore certain resources. Would the solution specified in #421 work for your use case?

Based on our conversation, I also heard from you that when we see a PR with a removed file, we should take the opportunity to instruct users (via GH comment) about the proper way to either 1) Remove, or 2) Ignore different resources.

**Comment by smoy** [comment]
ok, I can confirm I replicate this with latest version.

https://github.com/noqdev/iambic-templates-itest/pull/299 (internal repo), so not publicly visible. 

This is related to the git usage of iambic. When it retrieves list of changes, it see a modified file that is categorized as rename. (I copy template_1 as template_2, change the id inside template_2. proceed to do `git rm template_1` , `git add template_2`. git commit considers it as a rename. (shrugs).

iambic has business logic to create an in-memory file for the deleted contents. it attempts to check over during apply and then proceed to delete it. That logic is ok for actual template physically on the filesystem but not one that it creates in-memory.
