### ISSUE TITLE
Github Integration "RUN" Link broken

### ISSUE THREAD

**Issue by mxw-sec** [noqdev/iambic#431]
**Describe the bug**
User issues a PR and receives a plan or apply.  At the bottom of the comment is a "RUN" hyper link.  This link leads to a 404.
**To Reproduce**
1. Create a new Branch
2. Issue a PR
3. click on Run Hyperlink
4. receive 404

**Expected behavior**
link directs to completed output or log.

**Screenshots**
![image](https://github.com/noqdev/iambic/assets/106832227/932666f4-0ae5-4703-8c43-2d4e34b45b81)
![image](https://github.com/noqdev/iambic/assets/106832227/89c195e4-76f9-41cb-9a34-99ebe803b9b6)
![image](https://github.com/noqdev/iambic/assets/106832227/171e3b17-06ea-4d03-b059-3bb11c0478cd)

**Additional context**
I had a large run that the apply was truncated for. it asked to navigate to the link which is broken. 

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.

**Comment by castrapel** [comment]
Resolved by #432 (Lacking documentation on creation of gist repo)
