### ISSUE TITLE
Git Apply Flow is not including the exceptions messages in response of PR comments

### ISSUE THREAD

**Issue by smoy** [noqdev/iambic#507]
**Describe the bug**
Failures of apply is contained inside the TemplateChangeDeteails but is not rendered in the PR response. 

**To Reproduce**

1. include a invalid trust policy in a role
2. open a PR
3. Go through iambic plan, iambic apply
4. exceptions were not rendered in the PR, and the PR is merged.

**Expected behavior**
The Exceptions should been rendered correctly. and should NOT proceed to merge the branch. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.

**Comment by Will-NOQ** [comment]
This issue will be resolved once this change is merged in 
https://github.com/noqdev/iambic/pull/534/files#diff-11b5d483056839201c516f7494dcdbabc47eadcd577f5d1514a777b6dac6736a
