### ISSUE TITLE
Iambic Detect Fails AWS

### ISSUE THREAD

**Issue by Wilhite-r** [noqdev/iambic#631]
**Describe the bug**
Iambic detect fails on AWS because user group information is stored in a list as opposed to a dict.

**To Reproduce**

1. Go to AWS console
2. Perform IAM updates
3. Run Iambic Detect

**Expected behavior**
A list of expected import changes is written to a file

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu (WSL2 on Windows 11)

**Additional context**

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.

**Comment by Wilhite-r** [comment]
Opened a PR for this already: https://github.com/noqdev/iambic/pull/632

**Comment by smoy** [comment]
the `iambic-core` `0.11.86` includes the PR fix from #632 

thank you for the contribution: https://pypi.org/project/iambic-core/#history
