### ISSUE TITLE
Iambic Import not working successfully

### ISSUE THREAD

**Issue by MaxMoon771** [noqdev/iambic#677]
**Describe the bug**
We are implementing the open-source solution into our Gitlab environment and re-engineering the setup to work through its CI/CD Pipeline.   we have had a lot of testing success, and have been interested incorporating the import process into a workflow.  We are running into issues when the command runs through.

Error Message:
2024/06/26 14:12:59 [error    ] Unhandled Exception
  error=ValidationError(model='ServiceControlPolicyItem', errors=[{'loc': ('Description',), 'msg': 'field required', 'type': 'value_error.missing'}])
  exception=ValidationError
![image](https://github.com/noqdev/iambic/assets/173953079/07c48b9b-73a2-4231-8281-23d6bf0454d5)

Wondering if a AWS SCP is configured wrong from the expected formatting or what I might be missing.

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.

**Comment by WillNye** [comment]
Sorry for the delayed response, taking a look now

**Comment by WillNye** [comment]
Could you provide a redacted version of the SCP template you're attempting to apply? It looks like maybe the Description wasn't being provided. I double checked the boto3 docs and it is a required field.
